### ISSUE TITLE
input does not set the original value given

### ISSUE THREAD

**Issue by rhadoo200** [maestro-server/bootue#33]
Hi,

The bs-input component does not have a default value given. For example:

<bs-input :value="inputValue" :label="name"></bs-input>

data() {
return {
inputValue: 'my value'
}
}

In this case the input is created with a empty val. That's because you are creating the input like this:
<div :is="type=='textarea'?type:'input'" class="form-control" ref="input">

If you put a simple if/else it will work.

<div v-if="type=='textarea'">
      <textarea class="form-control" ref="input"
           :cols="cols"
           :disabled="disabled"
           :list="id_datalist"
           :name="name"
           :placeholder="placeholder"
           :readonly="readonly"
           :rows="rows"
           :title="attr(title)"
           v-model="val"
           @blur="emit" @focus="emit" @input="emit"></textarea>
    </div>
    <div v-else>
      <input class="form-control" ref="input"
                :cols="cols"
                :disabled="disabled"
                :list="id_datalist"
                :name="name"
                :placeholder="placeholder"
                :readonly="readonly"
                :rows="rows"
                :title="attr(title)"
                v-model="val"
                @blur="emit" @focus="emit" @input="emit"></input>
    </div>

If you don't want to duplicate the code make a custom render for this component without the template.html file.

Thanks

**Comment by rhadoo200** [comment]
i see that my code was stripped by github. i will write you an email with the problem.

**Comment by Signorini** [comment]
Hello, thanks, i release new patch version fix this issue
